png("plot3.png", width=480, height=480)
plot(file$DateTime, file$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(file$DateTime, file$Sub_metering_2, type="l", col="red")
lines(file$DateTime, file$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()
