png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(file$DateTime, file$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(file$DateTime, file$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(file$DateTime, file$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(file$DateTime, file$Sub_metering_2, type="l", col="red")
lines(file$DateTime, file$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
plot(file$DateTime, file$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
